Jd/backend stationen integrate
juliandierker/yUOShi pull request #322
Opened 2021-03-09 12:38 UTC by juliandierker

Provide Contexts for stations and station-tasks

2021-03-09 14:58 UTC, SmokyZone requested changes
Sieht eigentlich ganz stimmig aus :)
Der StationsContext brauch noch ein wenig überarbeitung, damit alle daten vorhanden sind.

2021-03-09 14:58 UTC, SmokyZone commented on imports/ui/student/StudentOverview.js
> +  currentPackage && console.log(currentPackage.stations);
console.log entfernen :)

2021-03-09 14:58 UTC, SmokyZone commented on imports/ui/student/Workspace.js
> +import LoggingOut from "../LogginOut";
Die File sollte umbenant werden. von LogginOut zo LoggingOut (Wahrung der Konsistenz)

2021-03-09 14:58 UTC, SmokyZone commented on imports/ui/student/Workspace.js
> +      currentStation={currentStation}
Da die Progressbar alle Startions Rendern muss, müssen hier nicht nur die currentStation, sondern auch die anderen stations mitgeliefert werden.

2021-03-09 14:58 UTC, SmokyZone commented on imports/ui/student/Workspace.js
> +  console.log(stations);
log

2021-03-09 14:58 UTC, SmokyZone commented on imports/ui/student/StationsContext.js
> +export const StationsContextProvider = ({ currentPackageId, children }) => {
ist es möglich die Tasks der anderen stations (die, die nicht currentStations sind) zu laden? Die werden auch in der ProgressBar benötigt.

2021-03-09 14:58 UTC, SmokyZone commented on imports/ui/student/StationsContext.js
> +  const updateStations = useCallback(async () => {
wann genau wird updateStations aufgerufen?

Falls es beim wechseln der currentStation passiert sollte besser nicht jedes mal getStations aufgerufen werden.
es würde ja hier reichen die stations nur 1 mal von der studip datenbank zu laden.
  
Falls es nur beim initialisieren passiert würde ich die Funktion initStations nennen.

Generell würde ich eher die Daten nur 1x laden wollen und den rest intern regeln. (Also schon beim initialisieren die stations mit den Tasks füllen.

2021-03-09 15:00 UTC, SmokyZone commented on imports/ui/student/Workspace.js
> +      currentStation={currentStation}
kann ich aber auch zu einem späteren zeitpunkt hinzufügen.
Die Daten liegen ja schon im StationsContext bereit

2021-03-16 11:16 UTC, juliandierker commented on imports/ui/student/Workspace.js
> +      currentStation={currentStation}
Das ist richtig die stations lassen sich über den context jederzeit abrufen

2021-03-16 15:17 UTC, juliandierker commented on imports/ui/student/StationsContext.js
> +export const StationsContextProvider = ({ currentPackageId, children }) => {
war doch mega easy.. klar ist das möglich

2021-03-16 20:12 UTC, SmokyZone requested changes
Da ist noch ein log :) ( und ein komischer import )

2021-03-16 20:12 UTC, SmokyZone commented on imports/ui/student/TasksContext.js
> +    console.log(currentStation);
log

2021-03-16 20:12 UTC, SmokyZone commented on imports/ui/student/TasksContext.js
> +import { faMeteor } from "@fortawesome/free-solid-svg-icons";
uhh wasn das?

2021-03-16 20:12 UTC, SmokyZone commented on imports/ui/student/StationsContext.js
> +  const updateStations = useCallback(async () => {
Das TODO reicht mir hier erstmal :)

2021-03-23 14:11 UTC, merged