fix whitescreen bug for dnd tasks
juliandierker/yUOShi pull request #440
Opened 2022-01-27 14:56 UTC by SmokyZone

2022-02-01 08:12 UTC, juliandierker commented on imports/ui/navigation_bar/NavigationBar.js
> +  console.log(isSolved(currentTask));
console.log

2022-02-01 08:12 UTC, juliandierker commented on imports/ui/navigation_bar/NavigationBar.js
> +      return false;
könntest du hier einmal `return <Loading />` testen ob das langsamer wird

2022-02-01 08:13 UTC, juliandierker requested changes
Kleinigkeiten

2022-02-04 10:36 UTC, SmokyZone commented on imports/ui/navigation_bar/NavigationBar.js
> +  console.log(isSolved(currentTask));
done

2022-02-04 10:38 UTC, SmokyZone commented on imports/ui/navigation_bar/NavigationBar.js
> +      return false;
ich weiss nicht was du da meinst. warum sollten wir bei dem Submit Button Loading anzeigen?

2022-02-07 10:19 UTC, merged